steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sample-service:$COMMIT_SHA', '.']
    dir: 'app/sample-service'

images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sample-service:$COMMIT_SHA'

substitutions:
  _LOCATION: us-central1
  _REPOSITORY: secure-delivery

options:
  logging: CLOUD_LOGGING_ONLY
